spin_manifest_version = 2

[application]
authors = ["Nikos Nikolakakis <nonicked@protonmail.com>"]
description = "A simple Go application running as WASM."
name = "wasm-go-demo-app"
version = "0.1.1"

[[trigger.http]]
route = "/..."
component = "wasm-go-demo-app"

[component.wasm-go-demo-app]
source = "main.wasm"
description = "A Go component that returns a message."
allowed_outbound_hosts = []
[component.wasm-go-demo-app.build]
command = "tinygo build -target wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]