apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wasm-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wasm-app
    spec:
      runtimeClassName: wasmtime-spin
      containers:
      - name: wasm-container
        image: ttl.sh/wasm-go-demo-app:v0.1.1
        command: ["/"]
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: wasm-service
spec:
  selector:
    app.kubernetes.io/name: wasm-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80